# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Today < Formula
  desc "RALF companion for the CLI"
  homepage "https://github.com/darmiel/today"
  version "1.3.0"

  depends_on "git"
  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/darmiel/today/releases/download/v1.3.0/today_Darwin_arm64.tar.gz"
      sha256 "dc4507bce9e0ff6f1cc7d13542129029fce1df19af7e69654b810ce38bfbb3de"

      def install
        ENV["GOPATH"] = buildpath
        path = buildpath/"src/github.com/darmiel/today"
        path.install Dir["*"]
        cd path do
          system "go", "build", "-o", "#{bin}/today"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/darmiel/today/releases/download/v1.3.0/today_Darwin_x86_64.tar.gz"
      sha256 "0a5e417d09599e5c3c92dc4a1c6989c31132146648c3e819e188f2c0ee678a99"

      def install
        ENV["GOPATH"] = buildpath
        path = buildpath/"src/github.com/darmiel/today"
        path.install Dir["*"]
        cd path do
          system "go", "build", "-o", "#{bin}/today"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darmiel/today/releases/download/v1.3.0/today_Linux_arm64.tar.gz"
      sha256 "200af908714b2eee61679816b2243aa8bf4f618ab322baa18a7ef334ebe25bf5"

      def install
        ENV["GOPATH"] = buildpath
        path = buildpath/"src/github.com/darmiel/today"
        path.install Dir["*"]
        cd path do
          system "go", "build", "-o", "#{bin}/today"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/darmiel/today/releases/download/v1.3.0/today_Linux_x86_64.tar.gz"
      sha256 "dbcd2d12cb3acbf36e40db4f1f7a4cda4e8f33df571dae67eea8fd7c4c1e376c"

      def install
        ENV["GOPATH"] = buildpath
        path = buildpath/"src/github.com/darmiel/today"
        path.install Dir["*"]
        cd path do
          system "go", "build", "-o", "#{bin}/today"
        end
      end
    end
  end

  head "https://github.com/darmiel/today.git"

  test do
    system "#{bin}/today --version"
  end
end
