# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Today < Formula
  desc "RALF companion for the CLI"
  homepage "https://github.com/darmiel/today"
  version "1.4.2"

  depends_on "git"
  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/darmiel/today/releases/download/v1.4.2/today_Darwin_arm64.tar.gz"
      sha256 "90c794a2b1997f10952c2fe56cd90f5e8844da08af6487fe9183ced3fedc2f49"

      def install
        ENV["GOPATH"] = buildpath
        path = buildpath/"src/github.com/darmiel/today"
        path.install Dir["*"]
        cd path do
          system "go", "build", "-o", "#{bin}/today"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/darmiel/today/releases/download/v1.4.2/today_Darwin_x86_64.tar.gz"
      sha256 "efba99fb89bafb7684960111ea13721a10c732dffed81c9bd5d8f7510073e302"

      def install
        ENV["GOPATH"] = buildpath
        path = buildpath/"src/github.com/darmiel/today"
        path.install Dir["*"]
        cd path do
          system "go", "build", "-o", "#{bin}/today"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/darmiel/today/releases/download/v1.4.2/today_Linux_x86_64.tar.gz"
      sha256 "3fef4ca587631f4e97dc2559e1d3b33eaff03df89ac1577739773bb96ae66e9b"

      def install
        ENV["GOPATH"] = buildpath
        path = buildpath/"src/github.com/darmiel/today"
        path.install Dir["*"]
        cd path do
          system "go", "build", "-o", "#{bin}/today"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darmiel/today/releases/download/v1.4.2/today_Linux_arm64.tar.gz"
      sha256 "b1e0910828842337319e1553ee939298bfe2ba71f00d2f7fab4b7ea80e7b6a4d"

      def install
        ENV["GOPATH"] = buildpath
        path = buildpath/"src/github.com/darmiel/today"
        path.install Dir["*"]
        cd path do
          system "go", "build", "-o", "#{bin}/today"
        end
      end
    end
  end

  head "https://github.com/darmiel/today.git"

  test do
    system "#{bin}/today --version"
  end
end
