# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Today < Formula
  desc "RALF companion for the CLI"
  homepage "https://github.com/darmiel/today"
  version "1.4.1"

  depends_on "git"
  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/darmiel/today/releases/download/v1.4.1/today_Darwin_x86_64.tar.gz"
      sha256 "6e4810030c13a0df3494c29a16b9d24921d6b4ef14934f5980bee30de2349592"

      def install
        ENV["GOPATH"] = buildpath
        path = buildpath/"src/github.com/darmiel/today"
        path.install Dir["*"]
        cd path do
          system "go", "build", "-o", "#{bin}/today"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/darmiel/today/releases/download/v1.4.1/today_Darwin_arm64.tar.gz"
      sha256 "4a598e57d676fe0f848d4cf06688d8e6e7ca996e78d2a283dc292b9268287300"

      def install
        ENV["GOPATH"] = buildpath
        path = buildpath/"src/github.com/darmiel/today"
        path.install Dir["*"]
        cd path do
          system "go", "build", "-o", "#{bin}/today"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darmiel/today/releases/download/v1.4.1/today_Linux_arm64.tar.gz"
      sha256 "4e72327648b6a563d22afe941f838a8033f4b81f84db41b5f9979f744d726d74"

      def install
        ENV["GOPATH"] = buildpath
        path = buildpath/"src/github.com/darmiel/today"
        path.install Dir["*"]
        cd path do
          system "go", "build", "-o", "#{bin}/today"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/darmiel/today/releases/download/v1.4.1/today_Linux_x86_64.tar.gz"
      sha256 "6c5ab37c152c7c291fd3a6530009ae7469928c3d4ed3f295e7233ba4b2089dd3"

      def install
        ENV["GOPATH"] = buildpath
        path = buildpath/"src/github.com/darmiel/today"
        path.install Dir["*"]
        cd path do
          system "go", "build", "-o", "#{bin}/today"
        end
      end
    end
  end

  head "https://github.com/darmiel/today.git"

  test do
    system "#{bin}/today --version"
  end
end
